import { CalendarDayConfig } from '../models/calendar.models';

export const CALENDAR_DAYS: CalendarDayConfig[] = [
  {
    day: 1,
    challengeType: 'riddle',
    funFactKey: 'funFacts.day1',
    challengeData: {
      riddleKey: 'challenges.riddle.day1.question',
      answerKey: ['candle', 'ljus', 'stearinljus'],
      hintKey: 'challenges.riddle.day1.hint',
    },
  },
  {
    day: 2,
    challengeType: 'hangman',
    funFactKey: 'funFacts.day2',
    challengeData: {
      word: 'mistletoe',
      wordSv: 'mistel',
      clueKey: 'challenges.hangman.day2.clue',
      hintKey: 'challenges.hangman.day2.hint',
    },
  },
  {
    day: 3,
    challengeType: 'wordScramble',
    funFactKey: 'funFacts.day3',
    challengeData: {
      word: 'snowflake',
      wordSv: 'snöflinga',
      clueKey: 'challenges.wordScramble.day3.clue',
      hintKey: 'challenges.wordScramble.day3.hint',
    },
  },
  {
    day: 4,
    challengeType: 'memoryCard',
    funFactKey: 'funFacts.day4',
    challengeData: {
      gridSize: 4,
      icons: ['🎅', '⛄', '🎄', '🎁', '⭐', '🔔', '🕯️', '🦌'],
    },
  },
  {
    day: 5,
    challengeType: 'riddle',
    funFactKey: 'funFacts.day5',
    challengeData: {
      riddleKey: 'challenges.riddle.day5.question',
      answerKey: ['christmas tree', 'julgran', 'gran'],
      hintKey: 'challenges.riddle.day5.hint',
    },
  },
  {
    day: 6,
    challengeType: 'rebus',
    funFactKey: 'funFacts.day6',
    challengeData: {
      rebusKey: 'challenges.rebus.day6.puzzle',
      answerKey: ['snowman', 'snögubbe'],
      hintKey: 'challenges.rebus.day6.hint',
    },
  },
  {
    day: 7,
    challengeType: 'wordSearch',
    funFactKey: 'funFacts.day7',
    challengeData: {
      grid: [
        ['S', 'N', 'O', 'W', 'B', 'A', 'L', 'L', 'X', 'M'],
        ['T', 'Q', 'P', 'W', 'Z', 'K', 'M', 'V', 'B', 'P'],
        ['A', 'L', 'I', 'G', 'H', 'T', 'S', 'Y', 'N', 'R'],
        ['R', 'M', 'X', 'Q', 'F', 'W', 'P', 'L', 'D', 'T'],
        ['Z', 'F', 'R', 'O', 'S', 'T', 'K', 'R', 'V', 'S'],
        ['K', 'V', 'B', 'N', 'M', 'Q', 'W', 'X', 'Y', 'F'],
        ['G', 'I', 'F', 'T', 'S', 'Z', 'L', 'P', 'T', 'T'],
      ],
      gridSv: [
        ['S', 'N', 'Ö', 'B', 'O', 'L', 'L', 'T', 'X', 'K'],
        ['T', 'Q', 'P', 'W', 'Z', 'K', 'M', 'O', 'V', 'R'],
        ['J', 'L', 'J', 'U', 'S', 'M', 'Q', 'M', 'B', 'W'],
        ['A', 'P', 'X', 'F', 'W', 'Y', 'N', 'T', 'L', 'Y'],
        ['R', 'Z', 'K', 'V', 'B', 'P', 'M', 'E', 'D', 'B'],
        ['N', 'M', 'Q', 'W', 'X', 'L', 'T', 'N', 'V', 'N'],
        ['A', 'G', 'Å', 'V', 'O', 'R', 'K', 'P', 'X', 'M'],
      ],
      words: ['SNOWBALL', 'LIGHTS', 'FROST', 'GIFTS', 'STAR'],
      wordsSv: ['SNÖBOLL', 'LJUS', 'TOMTEN', 'GÅVOR', 'STJÄRNA'],
    },
  },
  {
    day: 8,
    challengeType: 'hangman',
    funFactKey: 'funFacts.day8',
    challengeData: {
      word: 'stocking',
      wordSv: 'julstrumpa',
      clueKey: 'challenges.hangman.day8.clue',
      hintKey: 'challenges.hangman.day8.hint',
    },
  },
  {
    day: 9,
    challengeType: 'geometryDash',
    challengeData: {
      levelLength: 2400,
      scrollSpeed: 240,
      jumpForce: 800,
      gravity: 2000,
      obstacles: [
        { x: 400, width: 40, height: 80, type: 'candy' },
        { x: 650, width: 40, height: 100, type: 'candy' },
        { x: 900, width: 80, height: 60, type: 'platform' },
        { x: 1100, width: 100, height: 0, type: 'pit' },
        { x: 1350, width: 40, height: 90, type: 'candy' },
        { x: 1550, width: 60, height: 50, type: 'platform' },
        { x: 1750, width: 80, height: 0, type: 'pit' },
        { x: 2100, width: 60, height: 80, type: 'platform' },
        { x: 2200, width: 40, height: 180, type: 'candy' },
      ],
    },
    funFactKey: 'funFacts.day9',
  },
  {
    day: 10,
    challengeType: 'riddle',
    funFactKey: 'funFacts.day10',
    challengeData: {
      riddleKey: 'challenges.riddle.day10.question',
      answerKey: ['snow', 'snö'],
      hintKey: 'challenges.riddle.day10.hint',
    },
  },
  {
    day: 11,
    funFactKey: 'funFacts.day11',
  },
  {
    day: 12,
    challengeType: 'wordScramble',
    funFactKey: 'funFacts.day12',
    challengeData: {
      word: 'reindeer',
      wordSv: 'ren',
      clueKey: 'challenges.wordScramble.day12.clue',
      hintKey: 'challenges.wordScramble.day12.hint',
    },
  },
  {
    day: 13,
    challengeType: 'rebus',
    funFactKey: 'funFacts.day13',
    challengeData: {
      rebusKey: 'challenges.rebus.day13.puzzle',
      answerKey: ['christmas', 'jul'],
      hintKey: 'challenges.rebus.day13.hint',
    },
  },
  {
    day: 14,
    challengeType: 'hangman',
    funFactKey: 'funFacts.day14',
    challengeData: {
      word: 'sleigh',
      wordSv: 'släde',
      clueKey: 'challenges.hangman.day14.clue',
      hintKey: 'challenges.hangman.day14.hint',
    },
  },
  {
    day: 15,
    funFactKey: 'funFacts.day15',
  },
  {
    day: 16,
    challengeType: 'wordSearch',
    funFactKey: 'funFacts.day16',
    challengeData: {
      grid: [
        ['C', 'A', 'N', 'D', 'Y', 'C', 'A', 'N', 'E', 'W'],
        ['Q', 'M', 'X', 'Z', 'K', 'P', 'V', 'B', 'L', 'L'],
        ['O', 'R', 'N', 'A', 'M', 'E', 'N', 'T', 'F', 'F'],
        ['W', 'T', 'Y', 'L', 'Q', 'Z', 'M', 'K', 'V', 'M'],
        ['R', 'E', 'I', 'N', 'D', 'E', 'E', 'R', 'B', 'P'],
        ['E', 'X', 'W', 'P', 'M', 'K', 'T', 'Q', 'N', 'R'],
        ['A', 'C', 'A', 'R', 'O', 'L', 'S', 'V', 'Y', 'T'],
        ['T', 'Z', 'L', 'M', 'N', 'P', 'R', 'W', 'X', 'K'],
        ['H', 'Q', 'V', 'B', 'F', 'D', 'K', 'Y', 'L', 'S'],
      ],
      gridSv: [
        ['P', 'O', 'L', 'K', 'A', 'G', 'R', 'I', 'S', 'M'],
        ['Q', 'M', 'X', 'Z', 'K', 'P', 'V', 'B', 'T', 'X'],
        ['K', 'R', 'A', 'N', 'S', 'W', 'Y', 'L', 'A', 'W'],
        ['L', 'T', 'Y', 'L', 'Q', 'Z', 'M', 'K', 'V', 'Q'],
        ['R', 'E', 'N', 'A', 'R', 'F', 'D', 'W', 'B', 'Z'],
        ['M', 'P', 'V', 'B', 'N', 'X', 'Q', 'Y', 'L', 'K'],
        ['J', 'U', 'L', 'S', 'Å', 'N', 'G', 'E', 'R', 'T'],
        ['P', 'Z', 'K', 'M', 'W', 'Q', 'V', 'X', 'L', 'N'],
        ['N', 'Ö', 'T', 'T', 'E', 'R', 'K', 'Y', 'B', 'M'],
      ],
      words: ['CANDYCANE', 'REINDEER', 'ORNAMENT', 'WREATH', 'CAROLS'],
      wordsSv: ['POLKAGRIS', 'RENAR', 'KRANS', 'JUL', 'JULSÅNGER', 'NÖTTER'],
    },
  },
  {
    day: 17,
    challengeType: 'riddle',
    funFactKey: 'funFacts.day17',
    challengeData: {
      riddleKey: 'challenges.riddle.day17.question',
      answerKey: ['icicle', 'istapp'],
      hintKey: 'challenges.riddle.day17.hint',
    },
  },
  {
    day: 18,
    funFactKey: 'funFacts.day18',
  },
  {
    day: 19,
    challengeType: 'wordScramble',
    funFactKey: 'funFacts.day19',
    challengeData: {
      word: 'gingerbread',
      wordSv: 'pepparkaka',
      clueKey: 'challenges.wordScramble.day19.clue',
      hintKey: 'challenges.wordScramble.day19.hint',
    },
  },
  {
    day: 20,
    challengeType: 'hangman',
    funFactKey: 'funFacts.day20',
    challengeData: {
      word: 'nutcracker',
      wordSv: 'nötknäppare',
      clueKey: 'challenges.hangman.day20.clue',
      hintKey: 'challenges.hangman.day20.hint',
    },
  },
  {
    day: 21,
    challengeType: 'rebus',
    funFactKey: 'funFacts.day21',
    challengeData: {
      rebusKey: 'challenges.rebus.day21.puzzle',
      answerKey: ['winter', 'vinter'],
      hintKey: 'challenges.rebus.day21.hint',
    },
  },
  {
    day: 22,
    challengeType: 'geometryDash',
    challengeData: {
      levelLength: 4200,
      scrollSpeed: 280,
      jumpForce: 900,
      gravity: 2000,
      obstacles: [
        { x: 500, width: 40, height: 80, type: 'candy' },
        { x: 850, width: 90, height: 60, type: 'platform' },
        { x: 1000, width: 40, height: 150, type: 'candy' },
        { x: 1250, width: 120, height: 0, type: 'pit' },
        { x: 1440, width: 140, height: 360, type: 'ceilingCandy' },
        { x: 1650, width: 40, height: 100, type: 'candy' },
        { x: 2050, width: 140, height: 80, type: 'platform' },
        { x: 2250, width: 40, height: 150, type: 'candy' },
        { x: 2300, width: 100, height: 0, type: 'pit' },
        { x: 2550, width: 80, height: 70, type: 'platform' },
        { x: 2580, width: 40, height: 300, type: 'ceilingCandy' },
        { x: 2750, width: 40, height: 130, type: 'candy' },
        { x: 2950, width: 80, height: 85, type: 'platform' },
        { x: 3150, width: 40, height: 100, type: 'candy' },
        { x: 3350, width: 100, height: 0, type: 'pit' },
        { x: 3450, width: 200, height: 70, type: 'platform' },
        { x: 3680, width: 40, height: 300, type: 'ceilingCandy' },
      ],
    },
    funFactKey: 'funFacts.day22',
  },
  {
    day: 23,
    challengeType: 'wordSearch',
    funFactKey: 'funFacts.day23',
    challengeData: {
      grid: [
        ['B', 'E', 'L', 'L', 'S', 'X', 'Q', 'Z', 'M', 'L'],
        ['M', 'K', 'P', 'V', 'N', 'W', 'Y', 'L', 'T', 'P'],
        ['C', 'O', 'O', 'K', 'I', 'E', 'S', 'F', 'B', 'E'],
        ['H', 'Q', 'Z', 'M', 'R', 'K', 'V', 'W', 'X', 'A'],
        ['O', 'W', 'P', 'L', 'A', 'T', 'Y', 'N', 'Q', 'C'],
        ['L', 'X', 'M', 'I', 'R', 'A', 'C', 'L', 'E', 'E'],
        ['L', 'A', 'N', 'G', 'E', 'L', 'Z', 'P', 'W', 'L'],
        ['Y', 'Q', 'V', 'B', 'L', 'M', 'K', 'T', 'Y', 'K'],
        ['S', 'N', 'O', 'W', 'F', 'X', 'P', 'W', 'Z', 'T'],
      ],
      gridSv: [
        ['K', 'L', 'O', 'C', 'K', 'O', 'R', 'X', 'Q', 'G'],
        ['M', 'P', 'V', 'B', 'N', 'W', 'Y', 'L', 'T', 'E'],
        ['K', 'A', 'K', 'O', 'R', 'Z', 'M', 'F', 'K', 'L'],
        ['F', 'Q', 'W', 'P', 'I', 'X', 'V', 'B', 'Y', 'L'],
        ['R', 'M', 'K', 'U', 'N', 'D', 'E', 'R', 'Q', 'A'],
        ['I', 'X', 'V', 'B', 'P', 'M', 'Z', 'F', 'D', 'N'],
        ['D', 'Ä', 'N', 'G', 'E', 'L', 'K', 'Y', 'W', 'G'],
        ['W', 'Q', 'Z', 'M', 'V', 'B', 'N', 'P', 'X', 'E'],
        ['M', 'U', 'R', 'G', 'R', 'Ö', 'N', 'A', 'L', 'L'],
      ],
      words: ['BELLS', 'ANGEL', 'COOKIES', 'HOLLY', 'MIRACLE', 'PEACE', 'SNOW'],
      wordsSv: ['KLOCKOR', 'ÄNGEL', 'KAKOR', 'MURGRÖNA', 'UNDER', 'FRID', 'SNÖ'],
    },
  },
  {
    day: 24,
    challengeType: 'riddle',
    funFactKey: 'funFacts.day24',
    challengeData: {
      riddleKey: 'challenges.riddle.day24.question',
      answerKey: ['santa claus', 'santa', 'jultomten', 'tomten'],
      hintKey: 'challenges.riddle.day24.hint',
    },
  },
];
